from .opset import _float, _int, _ints, _null, _string


attrset = {
    'Add': [],
    'And': [],
    'BatchNormalization': [_float('epsilon', 1e-05), _float('momentum', 0.9), _int('training_mode', 0)],
    'Cast': [_int('to', 0)],
    'Clip': [_ints('consumed_inputs', []), _float('max', 0.0), _float('min', 0.0)],
    'Concat': [_int('axis', 0)],
    'Conv': [_string('auto_pad', 'NOTSET'), _ints('dilations', []), _int('group', 1),
             _ints('kernel_shape', []), _ints('pads', []), _ints('strides', [])],
    'Div': [],
    'Equal': [],
    'Exp': [],
    'Gather': [_int('axis', 0)],
    'GlobalAveragePool': [],
    'GlobalMaxPool': [],
    'Greater': [],
    'Identity': [],
    'LeakyRelu': [_float('alpha', 0.01)],
    'Less': [],
    'Log': [],
    'MatMul': [],
    'MaxPool': [_string('auto_pad', 'NOTSET'), _int('ceil_mode', 0), _ints('dilations', []),
                _ints('kernel_shape', []), _ints('pads', []), _int('storage_order', 0), _ints('strides', [])],
    'Mul': [],
    'Not': [],
    'Or': [],
    'Relu': [],
    'Reshape': [_int('allowzero', 0)],
    'Shape': [_null('end'), _int('start', 0)],
    'Sigmoid': [],
    'Slice': [_null('axes'), _ints('ends', []), _ints('starts', [])],
    'Softplus': [],
    'Split': [_int('axis', 0), _null('split')],
    'Sub': [],
    'Squeeze': [_null('axes')],
    'Tanh': [],
    'Tile': [],
    'Transpose': [_ints('perm', [])],
    'Xor': [],
}
